# Generated by Django 4.2 on 2026-08-09 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_admin_register_delete_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_register',
        ),
    ]
