# Generated by Django 4.2 on 2026-08-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_branch',
            name='profile_pic',
            field=models.FileField(upload_to='admin/gallery/branch_images/'),
        ),
        migrations.AlterField(
            model_name='login_designation',
            name='profile_pic',
            field=models.FileField(upload_to='admin/gallery/designation_images/'),
        ),
    ]
