# Generated by Django 4.2 on 2026-08-11 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_login_branch_profile_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_decor_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('item_qty', models.IntegerField(default=1)),
                ('item_price', models.IntegerField(default=1)),
                ('item_total', models.IntegerField(default=1)),
                ('item_advance', models.IntegerField(default=1)),
                ('item_final_amount', models.IntegerField(default=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_designation')),
            ],
        ),
    ]
