# Generated by Django 4.2 on 2026-08-11 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_admin_decor_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_decor_items',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_branch'),
        ),
        migrations.AlterField(
            model_name='admin_decor_items',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_department'),
        ),
        migrations.AlterField(
            model_name='admin_decor_items',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_designation'),
        ),
        migrations.AlterField(
            model_name='admin_decor_items',
            name='item_advance',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='admin_decor_items',
            name='item_final_amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='admin_decor_items',
            name='item_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='admin_decor_items',
            name='item_price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='admin_decor_items',
            name='item_qty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='admin_decor_items',
            name='item_total',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
