# Generated by Django 4.2 on 2026-08-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_admin_decor_items_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_decor_items',
            name='item_advance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='admin_decor_items',
            name='item_final_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
