# Generated by Django 4.2 on 2026-08-12 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_login_register_branch_login_register_department_and_more'),
        ('adminapp', '0008_alter_admin_decor_items_item_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_decor_items',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.login_register'),
        ),
    ]
