# Generated by Django 4.2 on 2026-08-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_admin_decor_items_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_decor_items',
            name='item_status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
