# Generated by Django 4.2 on 2026-08-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_login_register_branch_login_register_department_and_more'),
        ('adminapp', '0010_admin_decor_items_item_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=300, null=True)),
                ('customer_address', models.IntegerField(blank=True, default=1, null=True)),
                ('customer_contact', models.IntegerField(blank=True, default=1, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.login_register')),
            ],
        ),
    ]
