# Generated by Django 4.2 on 2026-08-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_admin_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_customer',
            name='customer_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
