# Generated by Django 4.2 on 2026-08-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_alter_admin_customer_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_decor_items',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.admin_customer'),
        ),
    ]
