# Generated by Django 4.2 on 2026-08-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_admin_decor_items_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_decor_items',
            name='item_advance',
        ),
        migrations.AddField(
            model_name='admin_customer',
            name='customer_advance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
