# Generated by Django 4.2 on 2026-08-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_remove_admin_decor_items_item_advance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_decor_items',
            name='customer',
        ),
        migrations.AddField(
            model_name='admin_decor_items',
            name='item_advance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='admin_Customer',
        ),
    ]
