# Generated by Django 4.2 on 2026-08-15 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_login_register_branch_login_register_department_and_more'),
        ('adminapp', '0015_remove_admin_decor_items_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_decor_items',
            name='item_advance',
        ),
        migrations.CreateModel(
            name='admin_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=300, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=300, null=True)),
                ('customer_contact', models.IntegerField(blank=True, default=1, null=True)),
                ('item_advance', models.IntegerField(blank=True, default=0, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.login_register')),
            ],
        ),
        migrations.AddField(
            model_name='admin_decor_items',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.admin_customer'),
        ),
    ]
