# Generated by Django 4.2 on 2026-08-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_admin_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_decor_items',
            name='item_advance',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
