# Generated by Django 4.2 on 2026-08-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_admin_decor_items_item_advance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_customer',
            old_name='item_advance',
            new_name='customer_advance',
        ),
    ]
