# Generated by Django 4.2 on 2026-08-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_rename_item_advance_admin_customer_customer_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_decor_items',
            name='item_payable_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
