# Generated by Django 4.2 on 2026-08-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_admin_decor_items_item_payable_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_customer',
            name='customer_payable_amt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
