# Generated by Django 4.2 on 2026-08-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_admin_customer_customer_payable_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_decor_items',
            name='subitem',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
