# Generated by Django 4.2 on 2026-08-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_admin_decor_items_subitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_customer',
            name='customer_total_amt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
