# Generated by Django 4.2 on 2026-08-31 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_login_register_branch_login_register_department_and_more'),
        ('adminapp', '0023_admin_customer_customer_total_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.login_register')),
            ],
        ),
    ]
