# Generated by Django 4.2 on 2026-09-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_admin_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_customer',
            name='customer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin_customer',
            name='customer_function_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='admin_customer',
            name='customer_theme',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='admin_customer',
            name='customer_venue',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='admin_decor_items',
            name='item_category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin_decor_items',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
