# Generated by Django 4.2 on 2026-09-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_login_register_branch_login_register_department_and_more'),
        ('adminapp', '0025_admin_customer_customer_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_decor_items',
            name='item_advance',
        ),
        migrations.RemoveField(
            model_name='admin_decor_items',
            name='item_category_id',
        ),
        migrations.RemoveField(
            model_name='admin_decor_items',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='admin_decor_items',
            name='subitem',
        ),
        migrations.AddField(
            model_name='admin_decor_items',
            name='item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.admin_category'),
        ),
        migrations.CreateModel(
            name='admin_decor_subitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subitem', models.CharField(blank=True, max_length=300, null=True)),
                ('sitem_qty', models.IntegerField(blank=True, default=1, null=True)),
                ('sitem_price', models.IntegerField(blank=True, default=1, null=True)),
                ('sitem_total', models.IntegerField(blank=True, default=1, null=True)),
                ('sitem_final_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('sitem_payable_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('sitem_status', models.CharField(blank=True, max_length=300, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.login_register')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.admin_customer')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_designation')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.admin_decor_items')),
                ('item_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.admin_category')),
            ],
        ),
    ]
