# Generated by Django 4.2 on 2026-09-07 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_login_register_branch_login_register_department_and_more'),
        ('adminapp', '0026_remove_admin_decor_items_item_advance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(blank=True, max_length=300, null=True)),
                ('gallery_img', models.FileField(upload_to='admin/gallery/Decor_images/')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.login_register')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.admin_customer')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_designation')),
            ],
        ),
        migrations.DeleteModel(
            name='admin_bill_amount',
        ),
    ]
