# Generated by Django 4.2 on 2026-09-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_admin_gallery_delete_admin_bill_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_gallery',
            name='gallery_img',
            field=models.FileField(blank=True, null=True, upload_to='admin/gallery/Decor_images/'),
        ),
    ]
