# Generated by Django 4.2 on 2026-09-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_alter_admin_gallery_gallery_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_decor_items',
            name='item_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin_decor_items',
            name='item_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
