# Generated by Django 4.2 on 2026-09-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_alter_admin_decor_items_item_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_decor_items',
            old_name='item_status',
            new_name='item_price_status',
        ),
        migrations.RenameField(
            model_name='admin_decor_subitems',
            old_name='sitem_status',
            new_name='sitem_empty_status',
        ),
        migrations.AddField(
            model_name='admin_decor_items',
            name='item_qty_status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='admin_decor_subitems',
            name='sitem_qty_status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='admin_decor_subitems',
            name='sitem_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin_decor_subitems',
            name='sitem_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
