# Generated by Django 4.2 on 2026-09-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0030_rename_item_status_admin_decor_items_item_price_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_decor_subitems',
            old_name='sitem_empty_status',
            new_name='sitem_price_status',
        ),
    ]
