# Generated by Django 4.2 on 2026-08-09 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('profile_pic', models.FileField(upload_to='home/gallery/branch_images/')),
            ],
        ),
        migrations.CreateModel(
            name='login_department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.login_branch')),
            ],
        ),
        migrations.CreateModel(
            name='login_designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('profile_pic', models.FileField(upload_to='home/gallery/designation_images/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.login_branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.login_department')),
            ],
        ),
        migrations.CreateModel(
            name='login_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('profile_pic', models.FileField(upload_to='home/gallery/profile_images/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.login_branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.login_department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.login_designation')),
            ],
        ),
    ]
