# Generated by Django 4.2 on 2026-08-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_department',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='login_designation',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='login_designation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='login_register',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='login_register',
            name='department',
        ),
        migrations.RemoveField(
            model_name='login_register',
            name='designation',
        ),
        migrations.DeleteModel(
            name='login_branch',
        ),
        migrations.DeleteModel(
            name='login_department',
        ),
        migrations.DeleteModel(
            name='login_designation',
        ),
    ]
