# Generated by Django 4.2 on 2026-08-09 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_initial'),
        ('homeapp', '0002_remove_login_department_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_register',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_branch'),
        ),
        migrations.AddField(
            model_name='login_register',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_department'),
        ),
        migrations.AddField(
            model_name='login_register',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.login_designation'),
        ),
    ]
